# config/database.yml
default: &default
  adapter: sqlserver
  encoding: utf8
  host: 192.168.0.12        # うまく行かないときは Windows 側 IP を記載
  port: 1433
  username: biru
  password: system9922
  pool: 10
  timeout: 5000          # ms
  database: BIRU30_DEV
  variables:
    sql_mode: ANSI_QUOTES
  options:
    default_schema: biru
    schema_search_path: biru

development:
  <<: *default
  database: BIRU30_DEV

test:
  <<: *default
  database: BIRU30_TEST

production:
  <<: *default
  host: 192.168.0.12        # うまく行かないときは Windows 側 IP を記載
  username: biru
  password: system9922
  database: BIRU30
  pool: <%= ENV.fetch("DB_POOL", 20) %>
